import java.io.File
import java.security.KeyStore
import java.security.MessageDigest
import java.util.Base64
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
}

// ===================== RELEASE SIGNING =====================
// Reads keystore info in this priority order:
//   1) Environment variables (used by GitHub Actions — see
//      .github/workflows/main.yml). The workflow decodes
//      KEYSTORE_BASE64 into  app/keystore/ghosttype-release.jks  and
//      exports KEYSTORE_PATH + the three passwords/alias.
//   2) keystore.properties file at project root (for local signed
//      builds). File is gitignored. Format:
//          storeFile=keystore/ghosttype-release.jks
//          storePassword=...
//          keyAlias=...
//          keyPassword=...
//   3) None — release build is unsigned (debug build still works).
val keystorePropsFile = rootProject.file("keystore.properties")
val keystoreProps = Properties().apply {
    if (keystorePropsFile.exists()) load(keystorePropsFile.inputStream())
}

fun envOrProp(envKey: String, propKey: String): String? =
    System.getenv(envKey) ?: keystoreProps.getProperty(propKey)

val signStorePath  = envOrProp("KEYSTORE_PATH",     "storeFile")
val signStorePass  = envOrProp("KEYSTORE_PASSWORD", "storePassword")
val signKeyAlias   = envOrProp("KEY_ALIAS",         "keyAlias")
val signKeyPass    = envOrProp("KEY_PASSWORD",      "keyPassword")

val canSignRelease = !signStorePath.isNullOrBlank() &&
        !signStorePass.isNullOrBlank() &&
        !signKeyAlias.isNullOrBlank() &&
        !signKeyPass.isNullOrBlank() &&
        rootProject.file(signStorePath!!).exists()

// ===================== SOURCE INTEGRITY CHECK =====================
val criticalSourceDir = file("src/main/java/com/ghosttype/security")
val integrityFile = file("security_integrity.properties")
val integrityProps = Properties()

val loadIntegrityProps by tasks.registering {
    doLast {
        if (integrityFile.exists()) {
            integrityFile.inputStream().use { integrityProps.load(it) }
        }
    }
}

val updateSourceHashes by tasks.registering {
    group = "ghosttype"
    description = "Updates security_integrity.properties after legitimate edits"
    doLast {
        val files = integrityProps.getProperty("source.files", "")
            .ifBlank { "PastebinSecrets.kt,Hardener.kt,ApprovalGate.kt,CrashGate.kt,UpdateGate.kt,Obf.kt,SecurityGuard.kt" }
            .split(",").map { it.trim() }
        val md = MessageDigest.getInstance("SHA-256")
        val lines = mutableListOf<String>()
        lines.add("# Auto-generated by Gradle task updateSourceHashes. Do not edit manually.")
        lines.add("source.files=${files.joinToString(",")}")
        for (f in files) {
            val src = File(criticalSourceDir, f)
            if (!src.exists()) { println("[GhostType] WARNING: $f not found — skipping"); continue }
            val hash = src.readBytes().let { md.digest(it) }.joinToString("") { "%02x".format(it) }
            lines.add("$f.sha256=$hash")
        }
        val allBytes = files.filter { File(criticalSourceDir, it).exists() }
            .flatMap { File(criticalSourceDir, it).readBytes().toList() }.toByteArray()
        lines.add("")
        lines.add("# Aggregate SHA-256 of all source files combined (in order above)")
        lines.add("aggregate.sha256=${md.digest(allBytes).joinToString("") { "%02x".format(it) }}")
        integrityFile.writeText(lines.joinToString("\n") + "\n")
        println("[GhostType] Updated source integrity hashes")
    }
}

val verifySourceIntegrity by tasks.registering {
    group = "ghosttype"
    description = "Verifies critical security source files haven't been tampered with"
    dependsOn(loadIntegrityProps)
    doLast {
        val srcList = integrityProps.getProperty("source.files", "").split(",").map { it.trim() }
        if (srcList.size < 2) { println("[GhostType] No integrity data — run updateSourceHashes first"); return@doLast }
        val md = MessageDigest.getInstance("SHA-256")
        var ok = true
        for (f in srcList) {
            val src = File(criticalSourceDir, f)
            if (!src.exists()) { println("[GhostType] WARNING: $f not found"); continue }
            val hash = src.readBytes().let { md.digest(it) }.joinToString("") { "%02x".format(it) }
            val expected = integrityProps.getProperty("$f.sha256", "")
            if (expected.isNotBlank() && hash != expected) {
                println("[ERROR] SECURITY INTEGRITY VIOLATION: $f")
                println("  Expected: $expected")
                println("  Actual:   $hash")
                ok = false
            }
        }
        if (!ok) throw GradleException("Source integrity check FAILED. If you made a legitimate change, run: ./gradlew updateSourceHashes")
        println("[GhostType] Source integrity check PASSED")
    }
}

// ===================== OBFUSCATED CONSTANTS GEN (v1.9) =====================
// Generates `ObfConstants.kt` at build time containing:
//   - EXPECTED_SIGNING_SHA256 — read from the actual release keystore
//     so SecurityGuard can pin against it at runtime. No human paste
//     step required.
//   - APPROVAL_URL, WHATSAPP_NUMBER, OWNER_NAME, etc. — XOR-encrypted
//     with a key derived from packageName + cert SHA. A thief who
//     re-signs the APK with their own keystore produces a different
//     derived key → every Obf.decode() returns garbage → app + IME
//     are stuck on the lock screen for the rest of that APK's life.
//
// For unsigned / debug builds (no keystore), we still generate the
// file but with IS_OBFUSCATED=false and plain-text values so dev
// iteration isn't blocked. SecurityGuard skips its checks in that
// mode so the keyboard remains usable.
val obfOutputDir = layout.buildDirectory.dir("generated/source/obf").get().asFile

fun computeKeystoreSha(jks: File, password: String, alias: String): String {
    return try {
        val ks = KeyStore.getInstance("JKS")
        jks.inputStream().use { stream -> ks.load(stream, password.toCharArray()) }
        val cert = ks.getCertificate(alias) ?: return ""
        MessageDigest.getInstance("SHA-256")
            .digest(cert.encoded)
            .joinToString("") { b -> "%02x".format(b) }
    } catch (e: Exception) {
        println("[GhostType obf] Failed to read keystore: ${e.message}")
        ""
    }
}

fun xorB64(plain: String, key: ByteArray): String {
    val pBytes = plain.toByteArray(Charsets.UTF_8)
    val out = ByteArray(pBytes.size)
    for (i in pBytes.indices) {
        out[i] = (pBytes[i].toInt() xor key[i % key.size].toInt()).toByte()
    }
    return Base64.getEncoder().encodeToString(out)
}

// Inline integrity check — runs inside generateObfConstants so it CANNOT be
// bypassed by removing task dependencies. Anyone who edits critical security
// files will get a build error here regardless of task wiring.
fun runInlineIntegrityCheck() {
    val srcList = listOf(
        "PastebinSecrets.kt", "Hardener.kt", "ApprovalGate.kt",
        "CrashGate.kt", "UpdateGate.kt", "Obf.kt", "SecurityGuard.kt"
    )
    if (!integrityFile.exists()) return
    integrityFile.inputStream().use { integrityProps.load(it) }
    val md = MessageDigest.getInstance("SHA-256")
    var ok = true
    for (f in srcList) {
        val src = File(criticalSourceDir, f)
        if (!src.exists()) continue
        val hash = src.readBytes().let { md.digest(it) }.joinToString("") { "%02x".format(it) }
        val expected = integrityProps.getProperty("$f.sha256", "")
        if (expected.isNotBlank() && hash != expected) {
            println("\n========================================================")
            println("  SECURITY INTEGRITY VIOLATION: $f")
            println("  Expected: $expected")
            println("  Actual:   $hash")
            println("========================================================\n")
            ok = false
        }
    }
    if (!ok) throw GradleException("Critical security files have been tampered with! Run ./gradlew updateSourceHashes only if you are the authorized owner.")
}

val generateObfConstants = tasks.register("generateObfConstants") {
    group = "ghosttype"
    description = "Generates encrypted constants bound to the release signing certificate."

    inputs.property("storePath", signStorePath ?: "none")
    inputs.property("alias", signKeyAlias ?: "none")
    inputs.property("canSign", canSignRelease)
    outputs.dir(obfOutputDir)

    doLast {
        // INLINE INTEGRITY CHECK — CANNOT BE REMOVED
        runInlineIntegrityCheck()
        val pkgName = "com.ghosttype"
        val plaintexts = linkedMapOf(
            "WHATSAPP_NUMBER"  to "923017787729",
            "OWNER_NAME"       to "CHAND",
            "OWNER_TEAM"       to "ATF Team",
            "INSTAGRAM_URL"    to "https://www.instagram.com/chand.tricker?igsh=c2dhbHFyZXdrZmpp",
            "WA_CHANNEL_URL"   to "https://whatsapp.com/channel/0029VaZrEGYIN9ih4PxcFQ33",
            "WA_COMMUNITY_URL" to "https://chat.whatsapp.com/HBBWmgTmpNl7OvG2MCpQtR?mode=gi_t",
            "TELEGRAM_URL"     to "https://t.me/Chandtrickers",
            "LICENSE_LINE"     to "CHAND \u00B7 ATF Team. All rights reserved.",
            // Branding label rendered on the long space bar. Stored XOR-encrypted
            // alongside contact info so APK editors can't change it to "I love
            // X" without re-signing the keystore (which would also invalidate
            // the approval URL — see ApprovalGate / SecurityGuard for the chain).
            "SPACE_LABEL"      to "CHAND TRICKER"
        )

        val sha: String
        val isReal: Boolean
        if (canSignRelease) {
            val computed = computeKeystoreSha(
                rootProject.file(signStorePath!!),
                signStorePass!!,
                signKeyAlias!!
            )
            if (computed.isNotEmpty()) {
                sha = computed
                isReal = true
                println("[GhostType obf] Bound constants to keystore SHA-256: $sha")
            } else {
                sha = "0".repeat(64)
                isReal = false
                println("[GhostType obf] Could not read keystore — falling back to plaintext mode.")
            }
        } else {
            sha = "0".repeat(64)
            isReal = false
            println("[GhostType obf] No keystore configured — generating plaintext (dev) constants.")
        }

        val seed = "ghosttype_obf_v1::$pkgName::$sha".toByteArray(Charsets.UTF_8)
        val key = MessageDigest.getInstance("SHA-256").digest(seed)

        val emitted = if (isReal) {
            plaintexts.mapValues { (_, v) -> xorB64(v, key) }
        } else {
            // Skip encryption in dev mode so Obf.decode (which short-circuits
            // when IS_OBFUSCATED == false) returns usable plaintext values.
            plaintexts
        }

        val pkgDir = File(obfOutputDir, "com/ghosttype/security")
        pkgDir.mkdirs()
        File(pkgDir, "ObfConstants.kt").writeText(buildString {
            append("// Auto-generated by Gradle task generateObfConstants. Do not edit.\n")
            append("package com.ghosttype.security\n\n")
            append("internal object ObfConstants {\n")
            append("    const val EXPECTED_SIGNING_SHA256: String = \"$sha\"\n")
            append("    const val IS_OBFUSCATED: Boolean = $isReal\n")
            for ((k, v) in emitted) {
                append("    const val $k: String = \"")
                append(v.replace("\\", "\\\\").replace("\"", "\\\""))
                append("\"\n")
            }
            append("}\n")
        })
    }
}

android {
    namespace = "com.ghosttype"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.ghosttype"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0.12"
        vectorDrawables { useSupportLibrary = true }
    }

    sourceSets {
        getByName("main") {
            // Hook the generated ObfConstants.kt into the main source set
            // so kotlinc / KSP / javac all pick it up alongside hand-written code.
            // Using `generateObfConstants.map { obfOutputDir }` (a Provider)
            // — instead of a bare File — propagates the implicit task
            // dependency to every consumer (including KSP), so Gradle 8.7+
            // strict task-dependency validation passes without needing
            // separate `dependsOn(...)` wiring for each compile/ksp task.
            java.srcDir(generateObfConstants.map { obfOutputDir })
        }
    }

    signingConfigs {
        if (canSignRelease) {
            create("release") {
                storeFile = rootProject.file(signStorePath!!)
                storePassword = signStorePass
                keyAlias = signKeyAlias
                keyPassword = signKeyPass
            }
        }
    }

    buildTypes {
        release {
            // v1.9 — R8 + resource shrinking enabled. proguard-rules.pro
            // keeps the Android-loaded entry points + Room reflection
            // surfaces + Compose runtime + the security module's exposed
            // APIs intact while obfuscating everything else.
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // v1.10 — INSTALLABILITY FIX. Earlier versions left the release
            // APK unsigned when no release keystore secrets were configured
            // on the GitHub Actions runner — Android then refused to install
            // it with the infamous "App not installed — package appears to
            // be invalid" error (modern Android requires APK Signature
            // Scheme v2/v3, which an unsigned APK doesn't satisfy).
            //
            // Now we ALWAYS attach a signing config: real release keystore
            // when available, otherwise fall back to the auto-generated
            // debug keystore so the artifact is at least signature-valid
            // and side-loadable. SecurityGuard will detect the debug-cert
            // SHA mismatch with the obfuscation-derived expected SHA and
            // skip its strict pinning (IS_OBFUSCATED is false in that path
            // — see generateObfConstants), so the keyboard stays usable in
            // dev/CI builds without a real signing key.
            signingConfig = if (canSignRelease) {
                signingConfigs.getByName("release")
            } else {
                println("[GhostType] No release keystore configured — release APK will be signed with the DEBUG key so it's still installable. Configure KEYSTORE_BASE64 secret in GitHub Actions for a production build.")
                signingConfigs.getByName("debug")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    buildFeatures {
        compose = true
        viewBinding = true
        buildConfig = true
    }
    composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }

    packaging {
        resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" }
    }
}

// ===================== TASK WIRING =====================
// Primary wiring is via the `srcDir(generateObfConstants.map { ... })`
// Provider in the android.sourceSets block above — that propagates the
// task dependency to every consumer (kotlinc, javac, KSP, lint, etc.)
// automatically and satisfies Gradle 8.7+ strict task-dependency
// validation.
//
// This afterEvaluate is a belt-and-suspenders fallback that also wires
// any compile* / ksp* / lint* task to depend on generateObfConstants,
// in case a future AGP/KSP version stops honouring the source-set
// Provider chain for some task type.
afterEvaluate {
    tasks.matching { t ->
        val n = t.name
        (n.startsWith("compile") &&
            (n.contains("Kotlin") || n.contains("JavaWith") || n.contains("Java"))) ||
            n.startsWith("ksp") ||
            n.startsWith("lint")
    }.configureEach {
        dependsOn(generateObfConstants)
        dependsOn(verifySourceIntegrity)
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    androidTestImplementation(composeBom)

    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.2")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.2")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.2")
    implementation("androidx.navigation:navigation-compose:2.7.7")

    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    debugImplementation("androidx.compose.ui:ui-tooling")

    implementation("androidx.documentfile:documentfile:1.0.1")

    implementation("androidx.room:room-runtime:2.6.1")
    implementation("androidx.room:room-ktx:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
    implementation("androidx.work:work-runtime-ktx:2.9.0")
    implementation("androidx.datastore:datastore-preferences:1.1.1")
    implementation("com.google.android.material:material:1.12.0")

    // v1.9 — used by ApprovalGate to fetch the GitHub-hosted Users.json.
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    // Coil — URL image loading for Compose
    implementation("io.coil-kt:coil-compose:2.6.0")

    // AdMob — Home banner ads
    implementation("com.google.android.gms:play-services-ads:23.2.0")
}
